version: "3.8"
services:
    node:
        build:
            context: ./
            dockerfile: Dockerfile.node
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        ports:
            - "8080:8080"